name: call-gitleaks

on:
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  actions: read
  id-token: write

jobs:
  run-gitleaks:
    uses: theangrytech-git/MSDO/.github/workflows/msdo-gitleaks.yml@main
    with:
      branch: main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
