name: MSDO Main Scan

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  actions: read
  security-events: write

jobs:
  run-msdo-scan:
    uses: theangrytech-git/MSDO/.github/workflows/msdo-reusable.yml@main
    with:
      branch: ${{ github.ref_name }}
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
