name: Use MSDO Reusable Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  security-checks:
    uses: theangrytech-git/MSDO/.github/workflows/msdo-reusable.yml@main
