name: MSDO Main Scan

on:
  push:
    branches: [main]
  workflow_call:
  workflow_dispatch:

jobs:
  run-msdo-scan:
    uses: theangrytech-git/MSDO/.github/workflows/msdo-reusable.yml@main
    with:
      branch: ${{ github.ref_name }}
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  run-secret-scan:
    uses: theangrytech-git/MSDO/.github/workflows/msdo-secret-scanning.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
